"""GBNF grammar generation for tool-call constrained decoding.

llama.cpp ships native GBNF support; llama-cpp-python exposes it via
``LlamaGrammar.from_string(gbnf)``. When the grammar object is passed to
``create_chat_completion`` (or ``create_completion``) the sampler masks
invalid next tokens at every decode step — the model can *only* emit
text the grammar permits.

This module builds GBNFs from a :class:`~edgevox.llm.tools.ToolRegistry`
so the model is forced to emit a syntactically-valid OpenAI-shaped tool
call. Three strategies, each tuned for a different agent-loop intent:

- :func:`tool_call_grammar` — single tool call, schema-constrained
  arguments. Use when ``tool_choice="required"`` (must call something).
- :func:`single_tool_grammar` — exactly one named tool, with its
  argument schema enforced. Use when ``tool_choice={"name": "X"}``.
- :func:`reply_or_tool_grammar` — top-level alternation between any
  short text reply and a tool call. Useful when ``tool_choice="auto"``
  and the developer wants malformed-JSON elimination without losing
  the model's ability to answer in plain words.

All three return a GBNF string. The caller wraps it via
``LlamaGrammar.from_string(...)`` and passes the result on
``LLM.complete(..., grammar=)``.

Why GBNF and not xgrammar / outlines / llguidance?

* GBNF is built into llama.cpp, no extra dep.
* Compilation is microseconds for typical 3-5-tool registries.
* When llama.cpp was built with ``-DLLAMA_LLGUIDANCE=ON`` the engine
  is automatically the much faster Lark-based llguidance — same API
  surface to us.

Limits worth knowing:

* GBNF doesn't enforce JSON-schema *semantics* like ``minimum``,
  ``pattern``, or cross-field constraints. We constrain shape (object
  keys, primitive types, enum alternations) — semantic correctness
  still relies on the model.
* The grammar is per-registry (per-tools-list). The registry's
  fingerprint is the cache key in :class:`GrammarCache`.
"""

from __future__ import annotations

import json
import logging
import re
import threading
from typing import Any

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def tool_call_grammar(tools: list[dict]) -> str:
    """Return a GBNF that allows exactly one tool call from ``tools``.

    The grammar accepts ``{"name": "<one of>", "arguments": {...}}``
    where ``arguments`` is a fixed-key object derived from each tool's
    JSON schema. Whitespace around tokens is permitted but constrained
    so the model can't drift into free text.

    Use this for ``tool_choice="required"`` — the model must emit a
    tool call.
    """
    if not tools:
        raise ValueError("tool_call_grammar() requires at least one tool")
    return _root_grammar(tools, allow_text_reply=False)


def single_tool_grammar(tool: dict) -> str:
    """Return a GBNF that forces a call to exactly ``tool``.

    Equivalent to ``tool_call_grammar([tool])`` but documented as the
    intent ``tool_choice={"name": tool.name}``.
    """
    return tool_call_grammar([tool])


def reply_or_tool_grammar(tools: list[dict]) -> str:
    """Return a GBNF allowing either a short text reply or a tool call.

    The text-reply branch matches any non-``{`` opening character — a
    cheap way to express "anything that isn't JSON". The tool-call
    branch is identical to :func:`tool_call_grammar`. Use this for
    ``tool_choice="auto"`` when malformed-JSON elimination is wanted
    without losing the plain-text answer path.
    """
    if not tools:
        # No tools → no need for the alternation; just allow free text.
        return _free_text_grammar()
    return _root_grammar(tools, allow_text_reply=True)


# ---------------------------------------------------------------------------
# GBNF assembly
# ---------------------------------------------------------------------------


_HEADER = r"""# Generated by edgevox.llm.grammars — do not hand-edit.
ws ::= [ \t\n]*
string ::= "\"" ( [^"\\\x00-\x1F] | "\\" ["\\/bfnrt] | "\\u" [0-9a-fA-F]{4} )* "\""
number ::= "-"? ([0-9] | [1-9] [0-9]*) ("." [0-9]+)? ([eE] [-+]? [0-9]+)?
boolean ::= "true" | "false"
null ::= "null"
"""


def _root_grammar(tools: list[dict], *, allow_text_reply: bool) -> str:
    parts: list[str] = [_HEADER]

    tool_call_alternatives: list[str] = []
    arg_rules: dict[str, str] = {}

    for idx, raw in enumerate(tools):
        fn = raw.get("function") if "function" in raw else raw
        if not isinstance(fn, dict):
            continue
        name = fn.get("name")
        if not isinstance(name, str) or not name:
            continue
        params = fn.get("parameters") if isinstance(fn.get("parameters"), dict) else {}
        arg_rule = f"args_{idx}"
        arg_rules[arg_rule] = _params_to_gbnf_object(params)
        tool_call_alternatives.append(_one_tool_call_rule(name, arg_rule))

    if not tool_call_alternatives:
        raise ValueError("no usable tools in registry; refusing to build grammar")

    if allow_text_reply:
        parts.append("root ::= text-reply | tool-call\n")
        parts.append(_TEXT_REPLY_RULE)
    else:
        parts.append("root ::= tool-call\n")

    parts.append("tool-call ::= " + " | ".join(tool_call_alternatives) + "\n")
    for name, rule in arg_rules.items():
        parts.append(f"{name} ::= {rule}\n")

    return "".join(parts)


# ``text-reply`` — any non-empty utterance that does not begin with ``{``.
# We use a strict character class that matches one non-brace opener then
# any printable ASCII / unicode-byte for the tail. Keeps the model from
# inventing a third syntactic alternative the loop wouldn't recognise.
_TEXT_REPLY_RULE = r"""text-reply ::= [^{ \t\n] ( [^\n] )*
"""


def _free_text_grammar() -> str:
    """Reply-only grammar (no tools registered)."""
    return _HEADER + "root ::= text-reply\n" + _TEXT_REPLY_RULE


def _one_tool_call_rule(tool_name: str, arg_rule: str) -> str:
    """Inline rule for one ``{"name":..., "arguments":...}`` envelope."""
    quoted = json.dumps(tool_name)  # safe quoting + escaping
    return (
        '"{" ws "\\"name\\"" ws ":" ws '
        + json.dumps(quoted)[1:-1].join(('"', '"'))
        + ' ws "," ws "\\"arguments\\"" ws ":" ws '
        + arg_rule
        + ' ws "}"'
    )


# ---------------------------------------------------------------------------
# JSON-schema → GBNF for the ``arguments`` object
# ---------------------------------------------------------------------------


def _params_to_gbnf_object(params: dict) -> str:
    """Convert a JSON-schema ``parameters`` object into a GBNF rule body.

    Supports the subset of JSON Schema actually used by the @tool
    decorator: object with named ``properties``, primitive ``type``s,
    and ``enum`` alternations. Nested objects / arrays fall back to a
    permissive any-JSON-value rule (we don't lose correctness, we just
    don't enforce shape on deeply-nested args).
    """
    if not isinstance(params, dict):
        return _ANY_VALUE_RULE
    if params.get("type") != "object":
        return _ANY_VALUE_RULE
    properties = params.get("properties") or {}
    if not isinstance(properties, dict) or not properties:
        # Object with no declared properties → permissive empty-or-arbitrary.
        return '"{" ws "}"'

    pieces: list[str] = []
    for i, (key, schema) in enumerate(properties.items()):
        if i > 0:
            pieces.append('ws "," ws')
        pieces.append(_quoted_literal(key))
        pieces.append('ws ":" ws')
        pieces.append(_value_rule(schema))
    return '"{" ws ' + " ".join(pieces) + ' ws "}"'


def _value_rule(schema: Any) -> str:
    if not isinstance(schema, dict):
        return _ANY_VALUE_RULE
    enum = schema.get("enum")
    if isinstance(enum, list) and enum:
        # Strict enum — emit alternation of literal JSON values.
        alts = [_literal_for_value(v) for v in enum]
        return "( " + " | ".join(alts) + " )"
    typ = schema.get("type")
    if isinstance(typ, list):
        # Union (e.g. ["integer","null"]) — alternation of primitive rules.
        return "( " + " | ".join(_primitive_rule(t) for t in typ) + " )"
    if isinstance(typ, str):
        return _primitive_rule(typ)
    return _ANY_VALUE_RULE


def _primitive_rule(typ: str) -> str:
    if typ == "string":
        return "string"
    if typ in ("integer", "number"):
        return "number"
    if typ == "boolean":
        return "boolean"
    if typ == "null":
        return "null"
    if typ in ("object", "array"):
        # Defer to the permissive any-value rule; the @tool decorator
        # rarely emits these, and constraining nested schemas is a
        # PR-N follow-up.
        return _ANY_VALUE_RULE
    return _ANY_VALUE_RULE


_ANY_VALUE_RULE = '( string | number | boolean | null | "{" ws "}" | "[" ws "]" )'


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


_GBNF_LITERAL_BAD_RE = re.compile(r'["\\]')


def _quoted_literal(key: str) -> str:
    """Render ``key`` as a GBNF terminal that matches the JSON-quoted
    form of the string. Handles backslash + quote escaping safely."""
    escaped = json.dumps(key)  # safe JSON string
    # Wrap each char as a GBNF literal character class to avoid
    # double-escape ambiguity. Using ``json.dumps`` on the whole thing
    # gives us a clean ``"\"key\""`` form we can drop in directly.
    return json.dumps(escaped)[1:-1].join(('"', '"'))


def _literal_for_value(value: Any) -> str:
    """Render a JSON-encoded literal as a GBNF terminal (matches it byte-for-byte)."""
    js = json.dumps(value, ensure_ascii=False)
    return json.dumps(js)[1:-1].join(('"', '"'))


# ---------------------------------------------------------------------------
# GrammarCache — keyed by registry fingerprint
# ---------------------------------------------------------------------------


class GrammarCache:
    """Process-local cache of compiled :class:`LlamaGrammar` objects.

    Keyed by ``(strategy, registry_fingerprint)`` where the fingerprint
    is a stable hash of the OpenAI tool schemas. Compilation is
    microseconds but loading is amortised across all turns of an
    agent's lifetime.

    Thread-safe — multiple agents may share one LLM and concurrently
    request grammars.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._cache: dict[tuple[str, str], Any] = {}

    def get(self, strategy: str, tools: list[dict]) -> Any | None:
        """Return a compiled grammar or ``None`` if llama-cpp is unavailable.

        Returns ``None`` (not raises) so callers can opt-out gracefully
        when the backend doesn't support GBNF — the agent loop falls
        back to the parser chain.
        """
        try:
            from llama_cpp import LlamaGrammar  # local import — keeps tests dep-light
        except Exception:
            log.debug("llama_cpp.LlamaGrammar unavailable; grammar disabled")
            return None

        if not tools:
            return None
        fp = _fingerprint(tools)
        key = (strategy, fp)
        with self._lock:
            cached = self._cache.get(key)
            if cached is not None:
                return cached
        # Build outside the lock — compilation can be slow on first call.
        if strategy == "tool":
            gbnf = tool_call_grammar(tools)
        elif strategy == "reply_or_tool":
            gbnf = reply_or_tool_grammar(tools)
        else:
            raise ValueError(f"unknown grammar strategy: {strategy!r}")
        try:
            grammar = LlamaGrammar.from_string(gbnf, verbose=False)
        except Exception:
            log.exception("Grammar compilation failed; falling back to no-grammar")
            return None
        with self._lock:
            self._cache[key] = grammar
        return grammar


def _fingerprint(tools: list[dict]) -> str:
    """Deterministic hash of the tools list for GrammarCache keying."""
    canonical = json.dumps(tools, sort_keys=True, separators=(",", ":"), default=str)
    # SHA-1 is plenty for a cache key; not a security primitive here.
    import hashlib

    return hashlib.sha1(canonical.encode("utf-8")).hexdigest()


__all__ = [
    "GrammarCache",
    "reply_or_tool_grammar",
    "single_tool_grammar",
    "tool_call_grammar",
]
